name: Frontend Tests

on:
  push:
    paths:
      - 'Frontend/**'
      - '.github/workflows/frontend-tests.yml'
  pull_request:
    paths:
      - 'Frontend/**'
      - '.github/workflows/frontend-tests.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
        working-directory: Frontend
      - name: Install Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
      - name: Run unit tests
        working-directory: Frontend
        env:
          CHROME_BIN: /usr/bin/chromium-browser
          CI: 'true'
        run: npm test -- --watch=false --browsers=ChromeHeadless
